# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.IntegerField()),
                ('request_id', models.BigIntegerField()),
                ('time', models.DateTimeField()),
                ('filename', models.TextField()),
                ('filetype', models.CharField(default='gz', max_length=32)),
                ('checksum', models.CharField(max_length=128)),
                ('save_path', models.TextField()),
                ('receive_time', models.DateTimeField()),
                ('start_process_time', models.DateTimeField(blank=True, null=True)),
                ('end_process_time', models.DateTimeField(blank=True, null=True)),
                ('process_status', models.IntegerField(default=2)),
                ('device_id', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='AuditManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=20)),
                ('user', models.CharField(blank=True, max_length=64)),
                ('time', models.DateTimeField()),
                ('event_type', models.CharField(max_length=64)),
                ('opt_type', models.CharField(max_length=64)),
                ('message', models.TextField(blank=True)),
                ('device_id', models.CharField(blank=True, default='170907020001', max_length=12)),
                ('is_send_command', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'audit_management',
            },
        ),
        migrations.CreateModel(
            name='AuditSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=64)),
                ('time', models.DateTimeField()),
                ('event_type', models.CharField(max_length=64)),
                ('opt_type', models.CharField(max_length=64)),
                ('message', models.TextField(blank=True)),
                ('report_time', models.DateTimeField()),
                ('device_id', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'audit_system',
            },
        ),
        migrations.CreateModel(
            name='ManagementCenterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(max_length=12)),
                ('soft_version', models.CharField(max_length=32)),
                ('organs', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('address_code', models.CharField(max_length=6)),
                ('contact', models.TextField()),
                ('mem_total', models.IntegerField(default=0)),
                ('interface', models.TextField()),
                ('cpu_info', models.TextField()),
                ('disk_info', models.TextField()),
                ('access_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'management_center_info',
            },
        ),
    ]
