# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20170907_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditmanagement',
            name='device_id',
            field=models.CharField(default='170907020001', max_length=12),
        ),
        migrations.AddField(
            model_name='auditmanagement',
            name='event_type',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditmanagement',
            name='opt_type',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditmanagement',
            name='report_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditmanagement',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
