# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20170908_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditmanagement',
            name='report_time',
        ),
    ]
