# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=64)),
                ('time', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'audit_management',
            },
        ),
    ]
