# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_remove_auditmanagement_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditmanagement',
            name='user',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
