# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20170908_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditmanagement',
            name='device_id',
            field=models.CharField(blank=True, default='170907020001', max_length=12),
        ),
    ]
