# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePluginRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=12)),
                ('plug_cmd_id', models.IntegerField()),
                ('is_valid', models.IntegerField(default=1)),
                ('release_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device_plug_relation',
            },
        ),
        migrations.CreateModel(
            name='PluginAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('alarm_id', models.CharField(blank=True, max_length=20)),
                ('plug_id', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('filename', models.CharField(max_length=64)),
                ('checksum', models.CharField(max_length=128)),
                ('filetype', models.CharField(blank=True, max_length=32)),
                ('device_id', models.CharField(max_length=12)),
                ('report_time', models.DateTimeField()),
                ('save_path', models.TextField()),
            ],
            options={
                'db_table': 'plugin_alarm',
            },
        ),
        migrations.CreateModel(
            name='PluginCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=20)),
                ('plug_type', models.CharField(blank=True, max_length=10)),
                ('plug_id', models.IntegerField()),
                ('plug_version', models.CharField(blank=True, max_length=16)),
                ('plug_config_version', models.CharField(blank=True, max_length=16)),
                ('cpu', models.IntegerField(default=0)),
                ('mem', models.IntegerField(default=0)),
                ('disk', models.IntegerField(default=0)),
                ('device_id_list', models.TextField(blank=True)),
                ('generate_time', models.DateTimeField()),
                ('plug_path', models.TextField(blank=True)),
                ('plug_policy_path', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'plugin_command',
            },
        ),
        migrations.CreateModel(
            name='PluginDetector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=128)),
                ('plug_type', models.CharField(blank=True, max_length=10)),
                ('plug_id', models.BigIntegerField()),
                ('plug_version', models.CharField(blank=True, max_length=16)),
                ('plug_config_version', models.CharField(blank=True, max_length=16)),
                ('cpu', models.IntegerField(default=0)),
                ('mem', models.IntegerField(default=0)),
                ('disk', models.IntegerField(default=0)),
                ('plug_status', models.IntegerField()),
                ('version', models.CharField(blank=True, max_length=32)),
                ('device_id_list', models.TextField(blank=True)),
                ('device_id_list_run', models.TextField(blank=True)),
                ('plug_on_device_status', models.TextField(blank=True)),
                ('generate_time', models.DateTimeField()),
                ('plug_path', models.TextField(blank=True)),
                ('plug_config_path', models.TextField(blank=True)),
                ('is_del', models.IntegerField()),
                ('plug_name', models.CharField(blank=True, max_length=64)),
                ('plug_config_name', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'plugin_detector',
            },
        ),
        migrations.CreateModel(
            name='PluginStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plug_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('device_id', models.CharField(max_length=12)),
                ('report_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'plugin_status',
            },
        ),
        migrations.CreateModel(
            name='PlugTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=32)),
                ('cmd', models.CharField(max_length=8)),
                ('num', models.IntegerField(default=0)),
                ('config', models.TextField()),
                ('generate_time', models.DateTimeField(blank=True, null=True)),
                ('release_time', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.IntegerField(default=1)),
                ('device_id', models.CharField(blank=True, max_length=12)),
                ('is_success', models.CharField(default='false', max_length=32)),
                ('success_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'plug_task',
            },
        ),
    ]
