<li onclick="selectProtoFwd(this);" value="00">所有厂商</li>
<li onclick="selectProtoFwd(this);" value="01">中孚</li>
<li onclick="selectProtoFwd(this);" value="02">蓝盾</li>
<li onclick="selectProtoFwd(this);" value="03">天融信</li>
<li onclick="selectProtoFwd(this);" value="04">鼎普</li>
<li onclick="selectProtoFwd(this);" value="05">网安</li>
<li onclick="selectProtoFwd(this);" value="06">信工所</li>
<li onclick="selectProtoFwd(this);" value="07">网神360</li>
<li onclick="selectProtoFwd(this);" value="08">金城</li>